homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: !secret home_elevation
  unit_system: imperial
  time_zone: America/Chicago
  customize: !include customize.yaml

# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  # Uncomment this to add a password (recommended!)
  #api_password: !secret http_password #legacy item unneeded 20181227
  # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
  # base_url: example.duckdns.org:8123

# Checks for available updates
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

#ZWAVE SETUP
zwave:
  usb_path: /dev/ttyACM0
  debug: true

climate:
  - platform: zwave

notify:
  - name: homeNotification
    platform: smtp
    sender: !secret email_sender
    recipient:
      - !secret email_primary
    server: localhost
    port: 25
    debug: true

automation: !include_dir_merge_list automations/
device_tracker: !include device_presence.yaml
group: !include_dir_merge_named groups/
history_graph: !include graphs/graphs.yaml
input_boolean: !include inputs/input_boolean.yaml
input_datetime: !include inputs/input_datetime.yaml
input_number: !include inputs/input_number.yaml
sensor: !include sensors/sensors.yaml
