- platform: pi_hole
  host: !secret pi_hole_address
  monitored_conditions:
    - ads_blocked_today
    - ads_percentage_today
    - dns_queries_today

- platform: speedtest
  monitored_conditions:
    - ping
    - download
    - upload

- platform: darksky
  api_key: 'ab75f3d8cdbb56d92e09077778a1e4d0'
  update_interval: '00:05'
  monitored_conditions:
    - summary
    - temperature
    - precip_type
    - precip_intensity
    - precip_probability
    - apparent_temperature
    - dew_point
    - wind_speed
    - wind_bearing
    - cloud_cover
    - humidity
    - pressure
    - temperature_max
    - temperature_min
    - apparent_temperature_max
    - apparent_temperature_min

- platform: time_date
  display_options:
    - 'date'
    - 'time'
