- platform: darksky
  api_key: !secret darksky_key
  update_interval: '00:05'
  monitored_conditions:
    - summary
    - temperature
    - precip_type
    - precip_intensity
    - precip_probability
    - apparent_temperature
    - dew_point
    - wind_speed
    - wind_bearing
    - cloud_cover
    - humidity
    - pressure
    - temperature_high
    - temperature_low
    - apparent_temperature_high
    - apparent_temperature_low
