########################################################
#     SENDS EMAIL WHEN FREEZER DOOR OPEN TOO LONG
########################################################
- alias: freezer_alert
  trigger:
    platform: state
    entity_id: input_boolean.send_test_mail
    to: 'on'
  action:
    service: notify.homeNotification
    data:
      title: 'FREEZER ALERT'
      message: 'Freezer open for longer than 5 minutes!'


#- alias: freezer_alert
#  trigger:
#    platform: state
#    entity_id: binary_sensor.send_test_mail
#    to: 'on'
#    for:
#      minutes: 5
#  action:
#    service: notify.homeNotification
#    data:
#      title: 'FREEZER ALERT'
#      message: 'Freezer open for longer than 5 minutes!'
